--------------------------------------------------------
--  颇老捞 积己凳 - 格夸老-3岿-21-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERTBL
--------------------------------------------------------

  CREATE TABLE "HR"."USERTBL" 
   (	"USERID" CHAR(8 BYTE), 
	"USERNAME" NVARCHAR2(10), 
	"BIRTHYEAR" NUMBER(4,0), 
	"ADDR" NCHAR(2), 
	"MOBILE1" CHAR(3 BYTE), 
	"MOBILE2" CHAR(8 BYTE), 
	"HEIGHT" NUMBER(3,0), 
	"MDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007008
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007008" ON "HR"."USERTBL" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERTBL
--------------------------------------------------------

  ALTER TABLE "HR"."USERTBL" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."USERTBL" MODIFY ("ADDR" NOT NULL ENABLE);
  ALTER TABLE "HR"."USERTBL" MODIFY ("BIRTHYEAR" NOT NULL ENABLE);
  ALTER TABLE "HR"."USERTBL" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."USERTBL" MODIFY ("USERID" NOT NULL ENABLE);
