--------------------------------------------------------
--  颇老捞 积己凳 - 格夸老-3岿-21-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BUYTBL
--------------------------------------------------------

  CREATE TABLE "HR"."BUYTBL" 
   (	"IDNUM" NUMBER(8,0), 
	"USERID" CHAR(8 BYTE), 
	"PRODNAME" NCHAR(8), 
	"GROUPNAME" NCHAR(4), 
	"PRICE" NUMBER(8,0), 
	"AMOUNT" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007014
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007014" ON "HR"."BUYTBL" ("IDNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BUYTBL
--------------------------------------------------------

  ALTER TABLE "HR"."BUYTBL" ADD PRIMARY KEY ("IDNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."BUYTBL" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "HR"."BUYTBL" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "HR"."BUYTBL" MODIFY ("PRODNAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."BUYTBL" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "HR"."BUYTBL" MODIFY ("IDNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BUYTBL
--------------------------------------------------------

  ALTER TABLE "HR"."BUYTBL" ADD FOREIGN KEY ("USERID")
	  REFERENCES "HR"."USERTBL" ("USERID") ENABLE;
